# Create a playbook that will change the BindIP in the db in>

---

# agent node name/ip
- hosts: db

# gather facts
  gather_facts: yes

# provide admin access
  become: true

# provide instructions
  tasks:
  - name: Restart and Enable Mongodb
    service: name=mongodb state=restarted enabled=yes

# ensure db is in a running state