# Create a playbook to provision nginx web server in the web-node
---
# Yaml/yml file starts with three dashes
# where do you want to install or run this playboo
- hosts: web

# find the facts (see the logs) - optional
  gather_facts: yes

# provide admin access to this playbook - use sudo
  become: true

# provide the actual instructions - install nginx
  tasks:
  - name: provision/install/configure Nginx
    apt: pkg=nginx state=present

# ensure nginx is running/enable